name: appcent
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.4
  html: ^0.15.0
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.0+1



  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/ic_launcher.png

  uses-material-design: true


flutter_native_splash:
  color: "#ffffff"
  image: assets/ic_launcher.png
  android: true
  ios: true
  android_12:
    image: assets/ic_launcher.png
    icon_background_color: "#000000"